spring:
  profiles:
    default: test

  datasource:
    url: jdbc:h2:mem:~/cafeKioskApplication
    driver-class-name: org.h2.Driver
    username: sa
    password:

  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  reactive:
    session:
      cookie:
        same-site: none

jwt:
  secret: GHsxq1XHyyg/9ol+SOwtSJUtTV1+Y8kBQCxmIvk2ghc=asdfasdfewqer
  expiration_time:
    access_token: 30000000000000000 # 5분
    refresh_token: 86400000000000000 # 일주일